name: wpacatalog
channels:
  - conda-forge
dependencies:
  - python=3.10
  - voila=0.5.5
  - ipywidgets=8.1.1
  - notebook
  - jupyterlab_widgets
  - pandas
  - pip
  - pip:
      - openpyxl
      - xlsxwriter
